import { Product } from '@/lib/store';

export const products: Product[] = [
  {
    _id: 'p1', name: 'Fresh Avocado',
    description: 'Premium Hass avocados, perfectly ripe and creamy. Great for salads, toast, and guacamole. Sourced directly from certified organic farms.',
    price: 149, originalPrice: 199,
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=400&fit=crop',
    category: 'Vegetables', badge: 'Sale', badgeColor: 'bg-rose-500',
    rating: 4.8, reviews: 124, inStock: true, unit: '1 pc (200g)', featured: true,
    nutrition: 'Calories 160 | Fat 15g | Fiber 7g | Vitamin K 26%',
    tags: ['Organic', 'Healthy Fats', 'Vitamin K'], origin: 'Tamil Nadu', shelfLife: '3-5 days',
  },
  {
    _id: 'p2', name: 'Organic Broccoli',
    description: 'Fresh green broccoli heads, packed with nutrients and fiber. Steaming retains maximum nutrition.',
    price: 89,
    image: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400&h=400&fit=crop',
    category: 'Vegetables', badge: 'New', badgeColor: 'bg-grocery-green',
    rating: 4.9, reviews: 89, inStock: true, unit: '1 pc (300g)', featured: true,
    nutrition: 'Calories 55 | Protein 3.7g | Vitamin C 149%',
    tags: ['Organic', 'High Fiber', 'Vitamin C'], origin: 'Ooty', shelfLife: '4-7 days',
  },
  {
    _id: 'p3', name: 'Green Apples',
    description: 'Crisp and tangy green apples from Kashmir. Perfect for snacking, juicing, or adding to salads.',
    price: 189,
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&h=400&fit=crop',
    category: 'Fresh Fruits', rating: 4.7, reviews: 156, inStock: true, unit: '1 kg', featured: true,
    nutrition: 'Calories 52 | Fiber 2.4g | Vitamin C 10%',
    tags: ['Fresh', 'Low Calorie', 'Vitamin C'], origin: 'Kashmir', shelfLife: '7-10 days',
  },
  {
    _id: 'p4', name: 'Bell Peppers (Mix)',
    description: 'Colorful bell peppers - red, yellow, and green. Sweet, crunchy, and perfect for stir-fries.',
    price: 99, originalPrice: 129,
    image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&h=400&fit=crop',
    category: 'Vegetables', badge: 'Sale', badgeColor: 'bg-rose-500',
    rating: 4.6, reviews: 78, inStock: true, unit: '500g', featured: true,
    nutrition: 'Calories 31 | Vitamin C 169% | Vitamin A 11%',
    tags: ['Colorful', 'Vitamin C', 'Stir-Fry'], origin: 'Karnataka', shelfLife: '5-7 days',
  },
  {
    _id: 'p5', name: 'Fresh Lettuce',
    description: 'Crisp iceberg lettuce, farm fresh. Ideal for salads, sandwiches, and burgers.',
    price: 49, originalPrice: 69,
    image: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400&h=400&fit=crop',
    category: 'Leafy Greens', badge: 'Sale', badgeColor: 'bg-rose-500',
    rating: 4.8, reviews: 203, inStock: true, unit: '1 pc', featured: true,
    nutrition: 'Calories 15 | Vitamin K 102% | Vitamin A 82%',
    tags: ['Fresh', 'Low Calorie', 'Hydrating'], origin: 'Maharashtra', shelfLife: '3-5 days',
  },
  {
    _id: 'p6', name: 'Fresh Orange Juice',
    description: '100% pure cold-pressed orange juice. No added sugar or preservatives. Packed with Vitamin C.',
    price: 149,
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400&h=400&fit=crop',
    category: 'Fresh Juices', badge: 'New', badgeColor: 'bg-grocery-green',
    rating: 4.9, reviews: 167, inStock: true, unit: '1L', featured: true,
    nutrition: 'Calories 45 | Vitamin C 124% | Potassium 10%',
    tags: ['No Sugar', 'Cold-Pressed', 'Vitamin C'], origin: 'Nagpur', shelfLife: '2-3 days',
  },
  {
    _id: 'p7', name: 'Organic Spinach',
    description: 'Tender baby spinach leaves. Rich in iron, vitamins, and perfect for palak paneer.',
    price: 59,
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop',
    category: 'Leafy Greens', rating: 4.7, reviews: 134, inStock: true, unit: '250g bunch', featured: false,
    nutrition: 'Calories 23 | Iron 15% | Vitamin A 188%',
    tags: ['Organic', 'Iron Rich', 'Superfood'], origin: 'Punjab', shelfLife: '2-4 days',
  },
  {
    _id: 'p8', name: 'Alphonso Mangoes',
    description: 'Premium Ratnagiri Alphonso mangoes. Sweet, juicy, and aromatic — the king of mangoes.',
    price: 599, originalPrice: 799,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=400&h=400&fit=crop',
    category: 'Fresh Fruits', badge: 'Sale', badgeColor: 'bg-rose-500',
    rating: 4.9, reviews: 312, inStock: true, unit: '1 dozen', featured: true,
    nutrition: 'Calories 60 | Vitamin A 25% | Vitamin C 46%',
    tags: ['Premium', 'Seasonal', 'Vitamin A'], origin: 'Ratnagiri', shelfLife: '3-5 days',
  },
  {
    _id: 'p9', name: 'Fresh Ginger',
    description: 'Aromatic fresh ginger root. Essential for Indian cooking, chai, and herbal remedies.',
    price: 69,
    image: 'https://images.unsplash.com/photo-1615484477778-ca3b77940c25?w=400&h=400&fit=crop',
    category: 'Herbs & Spices', rating: 4.5, reviews: 98, inStock: true, unit: '250g', featured: false,
    nutrition: 'Calories 80 | Gingerol | Anti-Inflammatory',
    tags: ['Anti-Inflammatory', 'Digestive', 'Essential'], origin: 'Kerala', shelfLife: '10-15 days',
  },
  {
    _id: 'p10', name: 'Organic Tomatoes',
    description: 'Vine-ripened organic tomatoes. Perfect for curries, salads, sandwiches, and sauces.',
    price: 79,
    image: 'https://images.unsplash.com/photo-1546470427-0d4db154ceb8?w=400&h=400&fit=crop',
    category: 'Vegetables', rating: 4.6, reviews: 145, inStock: true, unit: '1 kg', featured: false,
    nutrition: 'Calories 18 | Vitamin C 17% | Lycopene',
    tags: ['Organic', 'Lycopene', 'Versatile'], origin: 'Maharashtra', shelfLife: '5-7 days',
  },
  {
    _id: 'p11', name: 'Bananas',
    description: 'Fresh ripe bananas. Naturally sweet and energy-boosting. Perfect for smoothies and snacks.',
    price: 49,
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=400&fit=crop',
    category: 'Fresh Fruits', rating: 4.4, reviews: 267, inStock: true, unit: '1 dozen', featured: false,
    nutrition: 'Calories 89 | Potassium 12% | Vitamin B6 25%',
    tags: ['Energy', 'Potassium', 'Everyday'], origin: 'Tamil Nadu', shelfLife: '3-5 days',
  },
  {
    _id: 'p12', name: 'Fresh Coriander',
    description: 'Aromatic coriander leaves. Essential garnish for Indian dishes, chutneys, and raita.',
    price: 29,
    image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=400&fit=crop',
    category: 'Leafy Greens', rating: 4.3, reviews: 89, inStock: true, unit: '1 bunch', featured: false,
    nutrition: 'Calories 23 | Vitamin K 258% | Vitamin A 67%',
    tags: ['Garnish', 'Vitamin K', 'Aromatic'], origin: 'Local Farms', shelfLife: '2-3 days',
  },
  {
    _id: 'p13', name: 'Strawberries',
    description: 'Sweet and juicy strawberries. Perfect for desserts, smoothies, and breakfast bowls.',
    price: 299,
    image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&h=400&fit=crop',
    category: 'Fresh Fruits', badge: 'New', badgeColor: 'bg-grocery-green',
    rating: 4.8, reviews: 198, inStock: true, unit: '250g box', featured: true,
    nutrition: 'Calories 32 | Vitamin C 97% | Manganese 19%',
    tags: ['Antioxidant', 'Vitamin C', 'Berry'], origin: 'Mahabaleshwar', shelfLife: '2-3 days',
  },
  {
    _id: 'p14', name: 'Turmeric Powder',
    description: 'Pure organic turmeric powder. The golden spice with powerful anti-inflammatory properties.',
    price: 129,
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=400&h=400&fit=crop',
    category: 'Herbs & Spices', badge: 'Bestseller', badgeColor: 'bg-amber-500',
    rating: 4.7, reviews: 234, inStock: true, unit: '200g', featured: false,
    nutrition: 'Calories 312 | Curcumin | Iron 46%',
    tags: ['Superfood', 'Curcumin', 'Anti-Inflammatory'], origin: 'Erode', shelfLife: '6-12 months',
  },
  {
    _id: 'p15', name: 'Fresh Carrots',
    description: 'Crunchy organic carrots, rich in beta-carotene. Great for juicing, salads, and halwa.',
    price: 59,
    image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400&h=400&fit=crop',
    category: 'Vegetables', rating: 4.5, reviews: 112, inStock: true, unit: '500g', featured: false,
    nutrition: 'Calories 41 | Vitamin A 334% | Fiber 3.6g',
    tags: ['Beta-Carotene', 'Eye Health', 'Crunchy'], origin: 'Ooty', shelfLife: '7-10 days',
  },
  {
    _id: 'p16', name: 'Watermelon Juice',
    description: 'Refreshing cold-pressed watermelon juice with mint. Perfect for hot summers.',
    price: 99,
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=400&fit=crop',
    category: 'Fresh Juices', badge: 'Summer', badgeColor: 'bg-sky-500',
    rating: 4.6, reviews: 87, inStock: true, unit: '1L', featured: false,
    nutrition: 'Calories 30 | Vitamin C 21% | Hydrating',
    tags: ['Refreshing', 'Hydrating', 'Summer'], origin: 'Local', shelfLife: '1-2 days',
  },
  {
    _id: 'p17', name: 'Organic Potatoes',
    description: 'Farm-fresh potatoes. Versatile for every Indian recipe — aloo gobi, fries, and more.',
    price: 49,
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82ber508?w=400&h=400&fit=crop',
    category: 'Vegetables', rating: 4.4, reviews: 178, inStock: true, unit: '1 kg', featured: false,
    nutrition: 'Calories 77 | Potassium 20% | Vitamin C 32%',
    tags: ['Staple', 'Energy', 'Versatile'], origin: 'Punjab', shelfLife: '14-21 days',
  },
  {
    _id: 'p18', name: 'Mixed Fruit Basket',
    description: 'A curated basket of seasonal fresh fruits. Perfect for gifting and family health.',
    price: 799, originalPrice: 999,
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=400&h=400&fit=crop',
    category: 'Fresh Fruits', badge: 'Sale', badgeColor: 'bg-rose-500',
    rating: 4.9, reviews: 56, inStock: true, unit: '2 kg assorted', featured: true,
    nutrition: 'Mixed Vitamins | High Fiber | Natural Sugars',
    tags: ['Gift', 'Assorted', 'Premium'], origin: 'Various Farms', shelfLife: '5-7 days',
  },
  {
    _id: 'p19', name: 'Green Chillies',
    description: 'Spicy green chillies for your daily cooking needs. Adds the perfect kick to every dish.',
    price: 39,
    image: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=400&h=400&fit=crop',
    category: 'Vegetables', rating: 4.3, reviews: 156, inStock: true, unit: '250g', featured: false,
    nutrition: 'Calories 40 | Capsaicin | Vitamin C 242%',
    tags: ['Spicy', 'Capsaicin', 'Essential'], origin: 'Guntur', shelfLife: '5-7 days',
  },
  {
    _id: 'p20', name: 'Mixed Veggie Box',
    description: 'Weekly box of assorted organic vegetables. Save 20% with this curated selection.',
    price: 349, originalPrice: 449,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=400&fit=crop',
    category: 'Organic', badge: 'Save 20%', badgeColor: 'bg-rose-500',
    rating: 4.8, reviews: 89, inStock: true, unit: '3 kg box', featured: true,
    nutrition: 'Mixed Vitamins | High Fiber | Balanced Nutrition',
    tags: ['Value Pack', 'Weekly', 'Organic'], origin: 'Various Farms', shelfLife: '4-7 days',
  },
  {
    _id: 'p21', name: 'Organic Basil',
    description: 'Fresh organic basil leaves. Perfect for pasta, pizza, pesto, and Thai cuisine.',
    price: 45,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    category: 'Herbs & Spices', rating: 4.6, reviews: 67, inStock: true, unit: '1 bunch', featured: false,
    nutrition: 'Calories 23 | Vitamin K 345% | Anti-Bacterial',
    tags: ['Aromatic', 'Italian', 'Fresh'], origin: 'Local Farms', shelfLife: '2-3 days',
  },
  // ===== NEW PRODUCTS (22-45) =====
  {
    _id: 'p22', name: 'Red Onions',
    description: 'Premium red onions from Nashik. Essential base for every Indian curry and salad.',
    price: 39,
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400&h=400&fit=crop',
    category: 'Vegetables', rating: 4.4, reviews: 345, inStock: true, unit: '1 kg', featured: true,
    nutrition: 'Calories 40 | Vitamin C 12% | Quercetin',
    tags: ['Staple', 'Everyday', 'Nashik'], origin: 'Nashik', shelfLife: '14-30 days',
  },
  {
    _id: 'p23', name: 'Dragon Fruit',
    description: 'Exotic pink dragon fruit with sweet white flesh. Rich in antioxidants and stunning on plates.',
    price: 349,
    image: 'https://images.unsplash.com/photo-1527325678964-54921661f888?w=400&h=400&fit=crop',
    category: 'Fresh Fruits', badge: 'Exotic', badgeColor: 'bg-purple-500',
    rating: 4.6, reviews: 93, inStock: true, unit: '500g', featured: true,
    nutrition: 'Calories 60 | Vitamin C 34% | Magnesium 10%',
    tags: ['Exotic', 'Antioxidant', 'Superfood'], origin: 'Vietnam', shelfLife: '3-5 days',
  },
  {
    _id: 'p24', name: 'Kale Bunch',
    description: 'Dark leafy kale, a superfood powerhouse. Great for smoothies, chips, and salads.',
    price: 79,
    image: 'https://images.unsplash.com/photo-1525385133512-2f3bdd039054?w=400&h=400&fit=crop',
    category: 'Leafy Greens', badge: 'Superfood', badgeColor: 'bg-emerald-500',
    rating: 4.5, reviews: 67, inStock: true, unit: '1 bunch (200g)', featured: true,
    nutrition: 'Calories 49 | Vitamin K 684% | Vitamin C 200%',
    tags: ['Superfood', 'Detox', 'Vitamin K'], origin: 'Organic Farms', shelfLife: '4-7 days',
  },
  {
    _id: 'p25', name: 'Sweet Corn',
    description: 'Fresh sweet corn cobs. Boil, grill, or roast — perfect as a snack or in salads.',
    price: 69,
    image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&h=400&fit=crop',
    category: 'Vegetables', rating: 4.5, reviews: 112, inStock: true, unit: '2 pcs', featured: false,
    nutrition: 'Calories 96 | Fiber 3g | Vitamin B1 19%',
    tags: ['Fiber Rich', 'Snack', 'Versatile'], origin: 'Shimla', shelfLife: '3-5 days',
  },
  {
    _id: 'p26', name: 'Pomegranate',
    description: 'Premium Bhagwa pomegranates, ruby red arils bursting with sweet-tart juice.',
    price: 199,
    image: 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=400&h=400&fit=crop',
    category: 'Fresh Fruits', badge: 'Premium', badgeColor: 'bg-amber-500',
    rating: 4.8, reviews: 178, inStock: true, unit: '1 kg', featured: true,
    nutrition: 'Calories 83 | Vitamin C 17% | Fiber 4g',
    tags: ['Premium', 'Antioxidant', 'Iron Rich'], origin: 'Solapur', shelfLife: '7-10 days',
  },
  {
    _id: 'p27', name: 'Garlic (Fresh)',
    description: 'Farm-fresh garlic bulbs. A must-have for Indian tadka and gravies.',
    price: 59,
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=400&h=400&fit=crop',
    category: 'Herbs & Spices', rating: 4.6, reviews: 201, inStock: true, unit: '250g', featured: false,
    nutrition: 'Calories 149 | Allicin | Manganese 73%',
    tags: ['Immunity', 'Essential', 'Tadka'], origin: 'Rajasthan', shelfLife: '30-60 days',
  },
  {
    _id: 'p28', name: 'Pineapple',
    description: 'Sweet golden pineapple, perfect for juices, raita, and tropical desserts.',
    price: 129,
    image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400&h=400&fit=crop',
    category: 'Fresh Fruits', rating: 4.5, reviews: 89, inStock: true, unit: '1 pc (1kg)', featured: false,
    nutrition: 'Calories 82 | Vitamin C 131% | Manganese 76%',
    tags: ['Tropical', 'Bromelain', 'Vitamin C'], origin: 'Kerala', shelfLife: '3-5 days',
  },
  {
    _id: 'p29', name: 'Beetroot',
    description: 'Deep red beetroot, rich in iron and nitrates. Great for juice and salads.',
    price: 49,
    image: 'https://images.unsplash.com/photo-1615484477752-8f3d21e1a2d9?w=400&h=400&fit=crop',
    category: 'Vegetables', rating: 4.4, reviews: 76, inStock: true, unit: '500g', featured: false,
    nutrition: 'Calories 43 | Iron 12% | Folate 37%',
    tags: ['Iron Rich', 'Detox', 'Blood Health'], origin: 'Punjab', shelfLife: '10-14 days',
  },
  {
    _id: 'p30', name: 'Blueberries',
    description: 'Plump imported blueberries. Tiny but loaded with antioxidants and brain-boosting nutrients.',
    price: 399,
    image: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=400&h=400&fit=crop',
    category: 'Fresh Fruits', badge: 'Imported', badgeColor: 'bg-indigo-500',
    rating: 4.7, reviews: 134, inStock: true, unit: '125g pack', featured: true,
    nutrition: 'Calories 57 | Vitamin C 16% | Antioxidants',
    tags: ['Superfood', 'Brain Food', 'Antioxidant'], origin: 'USA', shelfLife: '5-7 days',
  },
  {
    _id: 'p31', name: 'Cucumber',
    description: 'Cool and refreshing cucumbers. Perfect for raita, salads, and detox water.',
    price: 39,
    image: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400&h=400&fit=crop',
    category: 'Vegetables', rating: 4.3, reviews: 167, inStock: true, unit: '500g', featured: false,
    nutrition: 'Calories 15 | Hydrating 96% | Vitamin K 21%',
    tags: ['Hydrating', 'Cooling', 'Low Calorie'], origin: 'Local Farms', shelfLife: '5-7 days',
  },
  {
    _id: 'p32', name: 'Amla Juice',
    description: 'Pure Indian gooseberry (amla) juice. The richest natural source of Vitamin C.',
    price: 179,
    image: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=400&h=400&fit=crop',
    category: 'Fresh Juices', badge: 'Health', badgeColor: 'bg-emerald-500',
    rating: 4.8, reviews: 112, inStock: true, unit: '500ml', featured: true,
    nutrition: 'Calories 25 | Vitamin C 600% | Iron 8%',
    tags: ['Superfood', 'Immunity', 'Ayurvedic'], origin: 'Pratapgarh', shelfLife: '3-5 days',
  },
  {
    _id: 'p33', name: 'Green Peas',
    description: 'Fresh green peas, sweet and tender. Perfect for matar paneer, pulao, and samosas.',
    price: 69,
    image: 'https://images.unsplash.com/photo-1567225591450-06036b3392a6?w=400&h=400&fit=crop',
    category: 'Vegetables', rating: 4.4, reviews: 134, inStock: true, unit: '500g', featured: false,
    nutrition: 'Calories 81 | Protein 5g | Fiber 5g',
    tags: ['Protein', 'Green', 'Staple'], origin: 'Punjab', shelfLife: '3-5 days',
  },
  {
    _id: 'p34', name: 'Grapes (Black)',
    description: 'Sweet and tangy black grapes. Great for snacking, juicing, and making raisins.',
    price: 149,
    image: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400&h=400&fit=crop',
    category: 'Fresh Fruits', rating: 4.5, reviews: 98, inStock: true, unit: '500g', featured: false,
    nutrition: 'Calories 69 | Resveratrol | Vitamin K 18%',
    tags: ['Resveratrol', 'Heart Health', 'Snack'], origin: 'Nashik', shelfLife: '5-7 days',
  },
  {
    _id: 'p35', name: 'Curry Leaves',
    description: 'Fresh aromatic curry leaves. Essential for South Indian tempering and dal tadka.',
    price: 19,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    category: 'Herbs & Spices', rating: 4.3, reviews: 87, inStock: true, unit: '1 bunch', featured: false,
    nutrition: 'Calories 108 | Fiber 6g | Iron',
    tags: ['Essential', 'Aromatic', 'South Indian'], origin: 'Tamil Nadu', shelfLife: '5-7 days',
  },
  {
    _id: 'p36', name: 'Mushrooms (Button)',
    description: 'Fresh white button mushrooms. Perfect for pizzas, pastas, stir-fries, and soups.',
    price: 99,
    image: 'https://images.unsplash.com/photo-1504545102780-26774c1bb073?w=400&h=400&fit=crop',
    category: 'Vegetables', badge: 'Popular', badgeColor: 'bg-grocery-green',
    rating: 4.5, reviews: 145, inStock: true, unit: '200g', featured: true,
    nutrition: 'Calories 22 | Protein 3.1g | Vitamin D 33%',
    tags: ['Low Calorie', 'Protein', 'Umami'], origin: 'Delhi NCR', shelfLife: '3-5 days',
  },
  {
    _id: 'p37', name: 'Coconut Water',
    description: 'Natural tender coconut water. Electrolyte-rich, refreshing, and 100% natural.',
    price: 69,
    image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400&h=400&fit=crop',
    category: 'Fresh Juices', rating: 4.7, reviews: 198, inStock: true, unit: '1L', featured: false,
    nutrition: 'Calories 19 | Potassium 17% | Electrolytes',
    tags: ['Natural', 'Electrolyte', 'Refreshing'], origin: 'Kerala', shelfLife: '1-2 days',
  },
  {
    _id: 'p38', name: 'Cauliflower',
    description: 'Clean white cauliflower heads. Versatile for gobi manchurian, aloo gobi, and low-carb rice.',
    price: 69,
    image: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&h=400&fit=crop',
    category: 'Vegetables', rating: 4.3, reviews: 112, inStock: true, unit: '1 pc (500g)', featured: false,
    nutrition: 'Calories 25 | Vitamin C 77% | Fiber 2g',
    tags: ['Low Carb', 'Versatile', 'Vitamin C'], origin: 'Ooty', shelfLife: '5-7 days',
  },
  {
    _id: 'p39', name: 'Mint Leaves',
    description: 'Fresh peppermint leaves. Perfect for chutney, raita, mojitos, and biryani garnish.',
    price: 19,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    category: 'Herbs & Spices', rating: 4.4, reviews: 78, inStock: true, unit: '1 bunch', featured: false,
    nutrition: 'Calories 44 | Iron 11% | Vitamin A 42%',
    tags: ['Refreshing', 'Digestive', 'Garnish'], origin: 'Local Farms', shelfLife: '2-3 days',
  },
  {
    _id: 'p40', name: 'Organic Eggs (6)',
    description: 'Free-range organic eggs from happy hens. Rich golden yolks packed with protein.',
    price: 99,
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&h=400&fit=crop',
    category: 'Organic', badge: 'Organic', badgeColor: 'bg-amber-600',
    rating: 4.8, reviews: 234, inStock: true, unit: '6 pcs', featured: true,
    nutrition: 'Calories 155 | Protein 13g | Vitamin D 21%',
    tags: ['Free Range', 'Protein', 'Organic'], origin: 'Pune', shelfLife: '10-14 days',
  },
  {
    _id: 'p41', name: 'Sweet Potato',
    description: 'Naturally sweet orange-fleshed sweet potatoes. Packed with beta-carotene and fiber.',
    price: 79,
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop',
    category: 'Vegetables', rating: 4.5, reviews: 67, inStock: true, unit: '500g', featured: false,
    nutrition: 'Calories 86 | Fiber 3g | Vitamin A 283%',
    tags: ['Beta-Carotene', 'Fiber', 'Energy'], origin: 'Odisha', shelfLife: '10-14 days',
  },
  {
    _id: 'p42', name: 'Papaya',
    description: 'Ripe orange papaya. Sweet, soft, and loaded with digestive enzymes.',
    price: 79,
    image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=400&h=400&fit=crop',
    category: 'Fresh Fruits', rating: 4.4, reviews: 89, inStock: true, unit: '1 pc (700g)', featured: false,
    nutrition: 'Calories 43 | Vitamin A 224% | Papain Enzyme',
    tags: ['Digestive', 'Vitamin A', 'Tropical'], origin: 'Andhra Pradesh', shelfLife: '3-5 days',
  },
  {
    _id: 'p43', name: 'Cherry Tomatoes',
    description: 'Sweet cherry tomatoes perfect for salads, pasta, and snacking. Bursting with flavor.',
    price: 129,
    image: 'https://images.unsplash.com/photo-1546470427-0d4db154ceb8?w=400&h=400&fit=crop',
    category: 'Vegetables', badge: 'Premium', badgeColor: 'bg-red-500',
    rating: 4.6, reviews: 76, inStock: true, unit: '250g', featured: true,
    nutrition: 'Calories 18 | Lycopene | Vitamin C 17%',
    tags: ['Snack', 'Salad', 'Lycopene'], origin: 'Israel', shelfLife: '5-7 days',
  },
  {
    _id: 'p44', name: 'Litchi',
    description: 'Fresh seasonal litchis, sweet and fragrant. A beloved Indian summer fruit.',
    price: 199,
    image: 'https://images.unsplash.com/photo-1527325678964-54921661f888?w=400&h=400&fit=crop',
    category: 'Fresh Fruits', badge: 'Seasonal', badgeColor: 'bg-pink-500',
    rating: 4.7, reviews: 123, inStock: true, unit: '500g', featured: true,
    nutrition: 'Calories 66 | Vitamin C 119% | Potassium',
    tags: ['Seasonal', 'Sweet', 'Summer'], origin: 'Muzaffarpur', shelfLife: '2-3 days',
  },
  {
    _id: 'p45', name: 'Organic Brown Rice',
    description: 'Unpolished organic brown rice. Nutty flavor, high fiber, and perfect for healthy meals.',
    price: 149,
    image: 'https://images.unsplash.com/photo-1590868309231-e006f37b003a?w=400&h=400&fit=crop',
    category: 'Organic', rating: 4.6, reviews: 98, inStock: true, unit: '1 kg', featured: false,
    nutrition: 'Calories 216 | Fiber 3.5g | Magnesium 21%',
    tags: ['Whole Grain', 'High Fiber', 'Healthy'], origin: 'Madhya Pradesh', shelfLife: '6-12 months',
  },
];

export const featuredProducts = products.filter((p) => p.featured);
export const categories = [
  { name: 'Fresh Fruits', count: 32, image: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/6833ccbfa961.webp', color: 'from-rose-100 to-rose-50', slug: 'Fresh Fruits' },
  { name: 'Vegetables', count: 28, image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=200&h=200&fit=crop', color: 'from-emerald-100 to-emerald-50', slug: 'Vegetables' },
  { name: 'Leafy Greens', count: 18, image: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/480b534feb78.png', color: 'from-lime-100 to-lime-50', slug: 'Leafy Greens' },
  { name: 'Herbs & Spices', count: 24, image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=200&h=200&fit=crop', color: 'from-amber-100 to-amber-50', slug: 'Herbs & Spices' },
  { name: 'Fresh Juices', count: 15, image: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=200&h=200&fit=crop', color: 'from-orange-100 to-orange-50', slug: 'Fresh Juices' },
  { name: 'Organic', count: 21, image: 'https://images.unsplash.com/photo-1590868309231-e006f37b003a?w=200&h=200&fit=crop', color: 'from-teal-100 to-teal-50', slug: 'Organic' },
];
